[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "https://fonts.googleapis.com/css?family=Cabin:700|Sarala:400"
  [headers.values]
    Cache-Control = "public, max-age=31536000"